### ISSUE TITLE
Third party libraries

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/ng-components#10]
| Library                                  | Include         | Wrap  |
|:-------------------------------|:--------------|--------:|
| [ng-bootstrap](https://ng-bootstrap.github.io) | ?| ? |
| [ngx-toastr](https://scttcper.github.io/ngx-toastr/) | ?| ? |
| [body-scroll-lock](https://github.com/willmcpo/body-scroll-lock) | ?| ? |
| etc. | ?| ? |

**Comment by yousifalraheem** [comment]
we decided to build components from scratch and avoid the use of third party libraries for efficiency
