### ISSUE TITLE
Shadow on card component (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/ng-components#131]
### Design decision 2020-03-24
![image](https://user-images.githubusercontent.com/45568194/77452007-b63baa00-6df5-11ea-9aee-e0c47f902c2f.png)

**Change**
- Drop shadow height: 0.375 rem (used to be 0.125 rem)
- Drop shadow colour: Black (used to be Grey 2)

Also, note that the drop shadow is located 0.375 rem below the card and is not included in the actual card height

**Details**
https://designlibrary.sebgroup.com/components/card/#specification

**Reasoning**
There are too many variations because the design has been unspecified. The goal is to align the design of all our components and frameworks. 

If this issue is not relevant to you, please comment and close it.

Thank you! :)
/Ulrika

**Comment by yousifalraheem** [comment]
This should be implemented in SEB Bootstrap
