### ISSUE TITLE
Grey background colour (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/ng-components#158]
### Design decision 2020-03-23
**Change**
Background colour: Grey 100 #F8F8F8

**Details**
https://designlibrary.sebgroup.com/visual-identity/colours/

**Reasoning**
Background colour can be grey or white. After discussions between Design management and Bootstrap, we have decided on which grey colour.

If this issue is not relevant to you, please comment and close it.
Thank you,
/Ulrika

**Comment by ulde01** [comment]
It this issue relevant here?

**Comment by hjalmers** [comment]
Nope, closing
