### ISSUE TITLE
Slider design (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/ng-components#194]
### Design update 2020-04-17
**Change**
Have a look at the specification (link below) because the component has been redesigned in a few ways, but a couple of details are:
- No chevron
- Line: Height 4 px, rounded corners 
- Thumb size: 24 x 24 px
- Hover state: Thumb is enlarged
- Focus state: Thumb is framed

![Slider-2020-04-17](https://user-images.githubusercontent.com/45568194/79566170-64afd380-80b2-11ea-822b-cbb2baf7f35f.png)

**Details** 
https://designlibrary.sebgroup.com/components/slider/#specification

**Component identifier**
component-slider

As always, act on it if relevant, comment and close if not. :)
/Ulrika, Design management

**Comment by yousifalraheem** [comment]
implemented
