### ISSUE TITLE
Dropdown with support for multi-select

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/ng-components#22]
- [ ] Basic dropdown component and service?
- [ ]  Should be possible to use custom container i.e. attach dropdown to body etc.
- [ ]  Use bootstrap class names and markup by default
- [ ]  Add/remove class to body when dropdown is shown/hidden
- [ ]  Use [body-scroll-lock](https://github.com/willmcpo/body-scroll-lock) to prevent background scroll on mobile devices
- [ ]  Ability to pass custom template
- [ ]  Ability to use position i.e. top, left, right etc.
- [ ]  Support for multi-select with checkboxes
- [ ]  Support for typeahead (filter options using input field)

**Comment by yousifalraheem** [comment]
implemented
