### ISSUE TITLE
Updated accordion design

### ISSUE THREAD

**Issue by ulde01** [sebgroup/ng-components#24]
### Design review March 27

The accordion has been updated. 

**Change**
- The green “tab border” is removed
- Font in header is 20 px, with the option of a sub header (14 px)
- Header cell height:  if header only 48 px, if sub header 64 px
- Grey hover is added on the header cell
- Content background is still white/none, with the option to make it grey
- Chevron (FontAwesome Light) points up/down (not right/down)
- Guidelines now include: "Use this component mainly for text content"

**Reason**
Many reasons. First of all, it was time to specify the component better. We have adjusted to fit users’ need with more efficient use of space. The direction of chevron is updated to show how it is animated. We also noticed that the component has been (too) content-heavy and added clearer guidelines. 

**Specification**
https://designlibrary.sebgroup.com/components/accordion/

![image](https://user-images.githubusercontent.com/45568194/57231398-bc2c6f00-701a-11e9-8947-91e4c8036ae0.png)

Let us know if you have any questions!
/Ulrika
Design management

**Comment by yousifalraheem** [comment]
@ulde01  updated and published
