### ISSUE TITLE
Checkboxes and radiobuttons height (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/ng-components#45]
**Design update 2019-10-01**

To align with the other form components, pls update the **height** to 44 px for 
- Checkboxes
- Radio buttons

![image](https://user-images.githubusercontent.com/45568194/65961416-cc743900-e456-11e9-9b3e-461c78f01e14.png)

Original discussion: https://github.com/sebgroup/design-library/issues/16

Thanks!
/Ulrika, Design management

**Comment by yousifalraheem** [comment]
implemented
