### ISSUE TITLE
Tooltip not showing content in v1.0.0-beta.12

### ISSUE THREAD

**Issue by Aurimas159** [sebgroup/ng-components#524]
**Describe the bug**
After updating version from v1.0.0-beta.10 to v1.0.0-beta.12 stopped seeing content what tooltip represents.

**To Reproduce**
```
 <sebng-tooltip [content]="'tooltip text">
        <sebng-checkbox ...>
        </sebng-checkbox>
 </sebng-tooltip>

```
**Expected behavior**
Expected to see checkbox and tooltip on hover.

**Screenshots**
![image](https://user-images.githubusercontent.com/71499017/93592961-d7074580-f9bb-11ea-8f64-af60bce28d17.png)

**Comment by yousifalraheem** [comment]
Thank you for submitting your first issue. We will look into it as soon as we can. If you want to address this issue yourself, please read our [contributing guide](https://github.com/sebgroup/react-components/blob/develop/CONTRIBUTING.md) and submit a pull request.

**Comment by omarVodiaK** [comment]
Hello @Aurimas159 
It looks like the code you posted to reproduce has a missing single quote
```HTML
 <sebng-tooltip [content]="'tooltip text'">
        <sebng-checkbox ...>
        </sebng-checkbox>
 </sebng-tooltip>
```
 but since it looks like the content attribute's value is a string i would like to suggest to go for this.
```HTML
<sebng-tooltip content="tooltip text">
        <sebng-checkbox ...>
        </sebng-checkbox>
 </sebng-tooltip>
```

**Comment by Aurimas159** [comment]
Hi @omarVodiaK 
Problem was not content="tooltip text" but <sebng-checkbox> inside tooltip was not rendering. And it was working on previous version beta.10. I will try todo other way, it is not a problem for me.
