### ISSUE TITLE
Badge (new component)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/ng-components#73]
### Design update 2020-01-13

**What is this?**
This component calls attention to a status/tag/category.
![image](https://user-images.githubusercontent.com/45568194/72283689-95114d00-363f-11ea-952d-556b86833a3e.png)

**Details**
See the specification to get all the right details:
https://designlibrary.sebgroup.com/components/badge/

**Component identifier**
component-badge

Thank you!
/Ulrika

**Comment by yousifalraheem** [comment]
The badge component is a UI element that has no JavaScript logic to it. Adding it to your code will only require HTML + Bootstrap classes like this:
```html
<div class="badge badge-success">Success</div>
```
For its simplicity, we decided not to create a component for it.
