### ISSUE TITLE
Library content

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/ng-components#8]
| Component                          | Type            | Issue    |
|:-------------------------------|:--------------|--------:|
| Accordion | component? ||
| Modal| component, service? | https://github.com/sebgroup/ng-components/issues/21 |
| Dropdown | component, service? | https://github.com/sebgroup/ng-components/issues/22 |
| Datepicker | component? ||
| Input feedback | directive? ||
| Button | directive ||
| Spinner/loader | structural directive, component |https://github.com/sebgroup/ng-components/issues/26|
| etc.| ||

**Comment by yousifalraheem** [comment]
all the mentioned components have been implemented
