### ISSUE TITLE
Change name of Alternative button to Button link

### ISSUE THREAD

**Issue by ulde01** [sebgroup/ng-components#82]
### Change
The button **Button link** used to be called Alternative button.
![image](https://user-images.githubusercontent.com/45568194/73255582-abcbae00-41c0-11ea-847c-77eba28105a8.png)

### Reason
The name Button link says what it is.

See the full specification here: 
https://designlibrary.sebgroup.com/components/forms/button/

Feel free to update this in your frameworks so that we use the same language on components. If this is not relevant to you, please close the issue with a comment. Thank you!

/Ulrika,
Design Management team

**Comment by yousifalraheem** [comment]
changed and published
